# Generated by Django 3.1.4 on 2021-03-11 06:37

import Api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50000, null=True)),
                ('createdby', models.CharField(max_length=500, null=True)),
                ('createdDate', models.DateTimeField()),
                ('updatedby', models.CharField(max_length=500, null=True)),
                ('updatedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Countrydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designationdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinPrimaryGroupLedgerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lgname', models.CharField(max_length=50)),
                ('pgname', models.CharField(max_length=50)),
                ('upgname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=50000, null=True)),
                ('motherName', models.CharField(max_length=50000, null=True)),
                ('bloodGroup', models.CharField(max_length=255, null=True)),
                ('parmanentAddress', models.CharField(max_length=1000000, null=True)),
                ('presentAddress', models.CharField(max_length=1000000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('ledger_image', models.ImageField(blank=True, default='ledimage/led.jpg', null=True, upload_to=Api.models.upload_to_led)),
                ('nid', models.CharField(max_length=200000, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.countrydb')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.district')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000)),
                ('primaryID', models.IntegerField(null=True)),
                ('upperGID', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(max_length=1000, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationName', models.CharField(max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GName', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='subledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('createdby', models.CharField(max_length=500, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedby', models.CharField(max_length=500, null=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_date', models.DateTimeField(auto_now_add=True)),
                ('recept_ammount_DR', models.IntegerField()),
                ('recept_ammount_CR', models.IntegerField()),
                ('invoice_number', models.CharField(blank=True, max_length=9)),
                ('createdby', models.CharField(max_length=500, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedby', models.CharField(max_length=500, null=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('narration', models.CharField(max_length=100000, null=True)),
                ('Branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.branchdb')),
                ('ledgeracoount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.ledgeraccount')),
                ('subledgerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.subledger')),
            ],
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='ledgerGroupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.ledgergroup'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='policeStation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.policestation'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_NID', models.CharField(max_length=100000)),
                ('employee_name', models.CharField(max_length=5000)),
                ('employee_gender', models.CharField(max_length=20, null=True)),
                ('employee_date_of_birth', models.CharField(max_length=255, null=True)),
                ('employee_address', models.CharField(max_length=5000, null=True)),
                ('employee_mobile', models.CharField(max_length=100, null=True)),
                ('employee_email', models.CharField(max_length=10000, null=True)),
                ('employee_joinning_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee_bacic', models.FloatField(null=True)),
                ('employee_status', models.IntegerField(null=True)),
                ('employee_qualification_dtails', models.CharField(max_length=20000, null=True)),
                ('employee_created_by', models.CharField(max_length=1000, null=True)),
                ('employee_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee_updated_by', models.CharField(max_length=1000, null=True)),
                ('employee_updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee_image', models.ImageField(blank=True, default='empimage/emp.jpg', null=True, upload_to=Api.models.upload_to)),
                ('employee_skills', models.CharField(max_length=20000, null=True)),
                ('employee_nic_name', models.CharField(max_length=1000, null=True)),
                ('employee_Father_name', models.CharField(max_length=1000, null=True)),
                ('employee_Mother_name', models.CharField(max_length=1000, null=True)),
                ('employee_sponsor_name', models.CharField(max_length=1000, null=True)),
                ('employee_village', models.CharField(max_length=50000, null=True)),
                ('employee_postoffice', models.CharField(max_length=50000, null=True)),
                ('employee_police_stations', models.CharField(max_length=50000, null=True)),
                ('employee_facebook_link', models.CharField(max_length=50000, null=True)),
                ('employee_District_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.district')),
                ('employee_branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.branchdb')),
                ('employee_degignation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.designationdb')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.IntegerField()),
                ('user_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=500)),
                ('createdby', models.CharField(max_length=500, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedby', models.CharField(max_length=500, null=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.employee')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.usertype')),
            ],
        ),
    ]
